dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "13"
cache:
  directories:
    - node_modules
install: npm install

before_script:
  - npm run ganache > /dev/null &
  - sleep 5
script:
  - npm run lint
  - npm run deploy-contracts
  - npm run build
  - npm run test
