/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { CustomOptions, contractOptions } from 'web3/eth/contract';
import { Contract, EventData } from 'web3-eth-contract';
import { TransactionObject, BlockType } from 'web3/eth/types';
import { PromiEvent, EventLog } from 'web3-core';
import { EventEmitter } from 'events';

export class RequestFactory extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  options: contractOptions;
  methods: {
    validateRequestParams(
      _addressArgs: (string)[],
      _uintArgs: (number | string)[],
      _endowment: number | string
    ): TransactionObject<(boolean)[]>;

    isKnownRequest(_address: string): TransactionObject<boolean>;

    getBucket(windowStart: number | string, unit: number | string): TransactionObject<string>;

    unpause(): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    pause(): TransactionObject<void>;

    transferOwnership(_newOwner: string): TransactionObject<void>;

    createRequest(
      _addressArgs: (string)[],
      _uintArgs: (number | string)[],
      _callData: (string | number[])[]
    ): TransactionObject<string>;

    createValidatedRequest(
      _addressArgs: (string)[],
      _uintArgs: (number | string)[],
      _callData: (string | number[])[]
    ): TransactionObject<string>;

    TIMESTAMP_BUCKET_SIZE(): TransactionObject<string>;
    paused(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    transactionRequestCore(): TransactionObject<string>;
    BLOCKS_BUCKET_SIZE(): TransactionObject<string>;
  };
  events: {
    ValidationError(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    Pause(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    Unpause(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    OwnershipRenounced(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    OwnershipTransferred(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    CloneCreated(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    RequestCreated(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ) => EventEmitter;
  };
}
