/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract } from 'web3-eth-contract';
import { ContractSendMethod } from 'web3-eth-contract';

export class SchedulerInterface extends Contract {
  methods: {
    computeEndowment(
      _bounty: number | string,
      _fee: number | string,
      _callGas: number | string,
      _callValue: number | string,
      _gasPrice: number | string
    ): ContractSendMethod<string>;

    schedule(
      _toAddress: string,
      _callData: string | number[],
      _uintArgs: (number | string)[]
    ): ContractSendMethod<string>;
  };
}
