/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractSendMethod, EventData } from 'web3-eth-contract';
import { BlockNumber } from 'web3-core';
import { EventEmitter } from 'events';

export interface TransactionRequestCoreRawData {
  0: (string)[];
  1: (boolean)[];
  2: (string)[];
  3: (string)[];
}

export class TransactionRequestCore extends Contract {
  methods: {
    requestData(): ContractSendMethod<TransactionRequestCoreRawData>;

    initialize(
      addressArgs: (string)[],
      uintArgs: (number | string)[],
      callData: (string | number[])[]
    ): ContractSendMethod<void>;

    execute(): ContractSendMethod<boolean>;

    cancel(): ContractSendMethod<boolean>;

    claim(): ContractSendMethod<boolean>;

    proxy(_to: string, _data: (string | number[])[]): ContractSendMethod<boolean>;

    refundClaimDeposit(): ContractSendMethod<boolean>;

    sendFee(): ContractSendMethod<boolean>;

    sendBounty(): ContractSendMethod<boolean>;

    sendOwnerEther(recipient: string): ContractSendMethod<boolean>;

    callData(): ContractSendMethod<(string)[]>;
  };
  events: {
    Aborted(
      options?: {
        filter?: object;
        fromBlock?: BlockNumber;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    Cancelled(
      options?: {
        filter?: object;
        fromBlock?: BlockNumber;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    Claimed(
      options?: {
        filter?: object;
        fromBlock?: BlockNumber;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    Executed(
      options?: {
        filter?: object;
        fromBlock?: BlockNumber;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockNumber;
        topics?: (null | string)[];
      },
      cb?: (error: Error, event: EventData) => void
    ) => EventEmitter;
  };
}
